services:
  lb:
    image: haproxy:alpine
    container_name: lb
    ports:
      - "9999:9999"
    volumes:
      - ./lb.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "25MB"

  api1:
    image: haproxy:alpine
    container_name: api1
    volumes:
      - ./api.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      core:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "25MB"

  api2:
    image: haproxy:alpine
    container_name: api2
    volumes:
      - ./api.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      core:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "25MB"

  core:
    image: ghcr.io/kauefsoares/rinha-backend-2026:latest
    container_name: core
    environment:
      - QUARKUS_HTTP_PORT=8080
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "exec 3<>/dev/tcp/localhost/8080 && printf 'GET /ready HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n' >&3 && read line <&3 && [ \"$$line\" = 'HTTP/1.1 200 OK\r' ]"
        ]
      interval: 1s
      timeout: 20s
      retries: 20
      start_period: 1s
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "275MB"